// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvVJzK4KHpUMt4nOEAyXiZq6k8rn9zHgE',
    appId: '1:865240502713:web:7c7a41b1da464d6df5a668',
    messagingSenderId: '865240502713',
    projectId: 'flutter-ecommerce-49ea8',
    authDomain: 'flutter-ecommerce-49ea8.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-49ea8.appspot.com',
    measurementId: 'G-671VKGZZZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCElQXpq_mUKB3yUo6rp4lDN9fvu6G1j5c',
    appId: '1:865240502713:android:def768b1ae74cb80f5a668',
    messagingSenderId: '865240502713',
    projectId: 'flutter-ecommerce-49ea8',
    storageBucket: 'flutter-ecommerce-49ea8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaKirTOBhsjUOF_Bk4heC6oCCb7aO8Jx0',
    appId: '1:865240502713:ios:a9eab119bf9d09e8f5a668',
    messagingSenderId: '865240502713',
    projectId: 'flutter-ecommerce-49ea8',
    storageBucket: 'flutter-ecommerce-49ea8.appspot.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaKirTOBhsjUOF_Bk4heC6oCCb7aO8Jx0',
    appId: '1:865240502713:ios:2383707658b2cd16f5a668',
    messagingSenderId: '865240502713',
    projectId: 'flutter-ecommerce-49ea8',
    storageBucket: 'flutter-ecommerce-49ea8.appspot.com',
    iosBundleId: 'com.example.ecommerceapp.RunnerTests',
  );
}
